class AsianPaintRunner {
	public static void main(String[] args) {

		AsianPaint asianpaint1 = new AsianPaint("Red", 10, 250.5f, "Glossy", 5.5f, true, "Asian", "India", 5, 3);
		System.out.println(asianpaint1.colorName);
		System.out.println(asianpaint1.quantity);
		System.out.println(asianpaint1.pricePerLitre);
		System.out.println(asianpaint1.finishType);
		System.out.println(asianpaint1.durability);
		System.out.println(asianpaint1.isWaterproof);
		System.out.println(asianpaint1.brand);
		System.out.println(asianpaint1.country);
		System.out.println(asianpaint1.rating);
		System.out.println(asianpaint1.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint2 = new AsianPaint("Blue", 8, 230.0f, "Matte", 4.5f, false, "Asian", "India", 4, 2);
		System.out.println(asianpaint2.colorName);
		System.out.println(asianpaint2.quantity);
		System.out.println(asianpaint2.pricePerLitre);
		System.out.println(asianpaint2.finishType);
		System.out.println(asianpaint2.durability);
		System.out.println(asianpaint2.isWaterproof);
		System.out.println(asianpaint2.brand);
		System.out.println(asianpaint2.country);
		System.out.println(asianpaint2.rating);
		System.out.println(asianpaint2.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint3 = new AsianPaint("Green", 12, 260.0f, "Glossy", 6.0f, true, "Asian", "India", 5, 4);
		System.out.println(asianpaint3.colorName);
		System.out.println(asianpaint3.quantity);
		System.out.println(asianpaint3.pricePerLitre);
		System.out.println(asianpaint3.finishType);
		System.out.println(asianpaint3.durability);
		System.out.println(asianpaint3.isWaterproof);
		System.out.println(asianpaint3.brand);
		System.out.println(asianpaint3.country);
		System.out.println(asianpaint3.rating);
		System.out.println(asianpaint3.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint4 = new AsianPaint("Yellow", 6, 210.0f, "Matte", 3.5f, false, "Asian", "India", 3, 2);
		System.out.println(asianpaint4.colorName);
		System.out.println(asianpaint4.quantity);
		System.out.println(asianpaint4.pricePerLitre);
		System.out.println(asianpaint4.finishType);
		System.out.println(asianpaint4.durability);
		System.out.println(asianpaint4.isWaterproof);
		System.out.println(asianpaint4.brand);
		System.out.println(asianpaint4.country);
		System.out.println(asianpaint4.rating);
		System.out.println(asianpaint4.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint5 = new AsianPaint("White", 15, 280.0f, "Glossy", 7.0f, true, "Asian", "India", 5, 5);
		System.out.println(asianpaint5.colorName);
		System.out.println(asianpaint5.quantity);
		System.out.println(asianpaint5.pricePerLitre);
		System.out.println(asianpaint5.finishType);
		System.out.println(asianpaint5.durability);
		System.out.println(asianpaint5.isWaterproof);
		System.out.println(asianpaint5.brand);
		System.out.println(asianpaint5.country);
		System.out.println(asianpaint5.rating);
		System.out.println(asianpaint5.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint6 = new AsianPaint("Black", 9, 240.0f, "Matte", 4.8f, true, "Asian", "India", 4, 3);
		System.out.println(asianpaint6.colorName);
		System.out.println(asianpaint6.quantity);
		System.out.println(asianpaint6.pricePerLitre);
		System.out.println(asianpaint6.finishType);
		System.out.println(asianpaint6.durability);
		System.out.println(asianpaint6.isWaterproof);
		System.out.println(asianpaint6.brand);
		System.out.println(asianpaint6.country);
		System.out.println(asianpaint6.rating);
		System.out.println(asianpaint6.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint7 = new AsianPaint("Orange", 7, 220.0f, "Glossy", 5.0f, false, "Asian", "India", 4, 2);
		System.out.println(asianpaint7.colorName);
		System.out.println(asianpaint7.quantity);
		System.out.println(asianpaint7.pricePerLitre);
		System.out.println(asianpaint7.finishType);
		System.out.println(asianpaint7.durability);
		System.out.println(asianpaint7.isWaterproof);
		System.out.println(asianpaint7.brand);
		System.out.println(asianpaint7.country);
		System.out.println(asianpaint7.rating);
		System.out.println(asianpaint7.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint8 = new AsianPaint("Pink", 5, 200.0f, "Matte", 3.0f, false, "Asian", "India", 3, 1);
		System.out.println(asianpaint8.colorName);
		System.out.println(asianpaint8.quantity);
		System.out.println(asianpaint8.pricePerLitre);
		System.out.println(asianpaint8.finishType);
		System.out.println(asianpaint8.durability);
		System.out.println(asianpaint8.isWaterproof);
		System.out.println(asianpaint8.brand);
		System.out.println(asianpaint8.country);
		System.out.println(asianpaint8.rating);
		System.out.println(asianpaint8.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint9 = new AsianPaint("Purple", 11, 255.0f, "Glossy", 5.8f, true, "Asian", "India", 5, 4);
		System.out.println(asianpaint9.colorName);
		System.out.println(asianpaint9.quantity);
		System.out.println(asianpaint9.pricePerLitre);
		System.out.println(asianpaint9.finishType);
		System.out.println(asianpaint9.durability);
		System.out.println(asianpaint9.isWaterproof);
		System.out.println(asianpaint9.brand);
		System.out.println(asianpaint9.country);
		System.out.println(asianpaint9.rating);
		System.out.println(asianpaint9.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint10 = new AsianPaint("Gray", 10, 245.0f, "Matte", 4.6f, true, "Asian", "India", 4, 3);
		System.out.println(asianpaint10.colorName);
		System.out.println(asianpaint10.quantity);
		System.out.println(asianpaint10.pricePerLitre);
		System.out.println(asianpaint10.finishType);
		System.out.println(asianpaint10.durability);
		System.out.println(asianpaint10.isWaterproof);
		System.out.println(asianpaint10.brand);
		System.out.println(asianpaint10.country);
		System.out.println(asianpaint10.rating);
		System.out.println(asianpaint10.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint11 = new AsianPaint("SkyBlue", 8, 230.0f, "Glossy", 5.2f, true, "Asian", "India", 4, 3);
		System.out.println(asianpaint11.colorName);
		System.out.println(asianpaint11.quantity);
		System.out.println(asianpaint11.pricePerLitre);
		System.out.println(asianpaint11.finishType);
		System.out.println(asianpaint11.durability);
		System.out.println(asianpaint11.isWaterproof);
		System.out.println(asianpaint11.brand);
		System.out.println(asianpaint11.country);
		System.out.println(asianpaint11.rating);
		System.out.println(asianpaint11.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint12 = new AsianPaint("Brown", 9, 240.0f, "Matte", 4.5f, false, "Asian", "India", 4, 2);
		System.out.println(asianpaint12.colorName);
		System.out.println(asianpaint12.quantity);
		System.out.println(asianpaint12.pricePerLitre);
		System.out.println(asianpaint12.finishType);
		System.out.println(asianpaint12.durability);
		System.out.println(asianpaint12.isWaterproof);
		System.out.println(asianpaint12.brand);
		System.out.println(asianpaint12.country);
		System.out.println(asianpaint12.rating);
		System.out.println(asianpaint12.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint13 = new AsianPaint("Cream", 6, 210.0f, "Glossy", 3.9f, true, "Asian", "India", 3, 2);
		System.out.println(asianpaint13.colorName);
		System.out.println(asianpaint13.quantity);
		System.out.println(asianpaint13.pricePerLitre);
		System.out.println(asianpaint13.finishType);
		System.out.println(asianpaint13.durability);
		System.out.println(asianpaint13.isWaterproof);
		System.out.println(asianpaint13.brand);
		System.out.println(asianpaint13.country);
		System.out.println(asianpaint13.rating);
		System.out.println(asianpaint13.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint14 = new AsianPaint("Gold", 5, 300.0f, "Glossy", 6.5f, true, "Asian", "India", 5, 5);
		System.out.println(asianpaint14.colorName);
		System.out.println(asianpaint14.quantity);
		System.out.println(asianpaint14.pricePerLitre);
		System.out.println(asianpaint14.finishType);
		System.out.println(asianpaint14.durability);
		System.out.println(asianpaint14.isWaterproof);
		System.out.println(asianpaint14.brand);
		System.out.println(asianpaint14.country);
		System.out.println(asianpaint14.rating);
		System.out.println(asianpaint14.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint15 = new AsianPaint("Silver", 7, 270.0f, "Matte", 5.0f, true, "Asian", "India", 4, 3);
		System.out.println(asianpaint15.colorName);
		System.out.println(asianpaint15.quantity);
		System.out.println(asianpaint15.pricePerLitre);
		System.out.println(asianpaint15.finishType);
		System.out.println(asianpaint15.durability);
		System.out.println(asianpaint15.isWaterproof);
		System.out.println(asianpaint15.brand);
		System.out.println(asianpaint15.country);
		System.out.println(asianpaint15.rating);
		System.out.println(asianpaint15.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint16 = new AsianPaint("Maroon", 10, 250.0f, "Glossy", 5.5f, true, "Asian", "India", 5, 4);
		System.out.println(asianpaint16.colorName);
		System.out.println(asianpaint16.quantity);
		System.out.println(asianpaint16.pricePerLitre);
		System.out.println(asianpaint16.finishType);
		System.out.println(asianpaint16.durability);
		System.out.println(asianpaint16.isWaterproof);
		System.out.println(asianpaint16.brand);
		System.out.println(asianpaint16.country);
		System.out.println(asianpaint16.rating);
		System.out.println(asianpaint16.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint17 = new AsianPaint("Teal", 8, 230.0f, "Matte", 4.2f, false, "Asian", "India", 3, 2);
		System.out.println(asianpaint17.colorName);
		System.out.println(asianpaint17.quantity);
		System.out.println(asianpaint17.pricePerLitre);
		System.out.println(asianpaint17.finishType);
		System.out.println(asianpaint17.durability);
		System.out.println(asianpaint17.isWaterproof);
		System.out.println(asianpaint17.brand);
		System.out.println(asianpaint17.country);
		System.out.println(asianpaint17.rating);
		System.out.println(asianpaint17.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint18 = new AsianPaint("Lavender", 6, 210.0f, "Glossy", 3.8f, true, "Asian", "India", 3, 2);
		System.out.println(asianpaint18.colorName);
		System.out.println(asianpaint18.quantity);
		System.out.println(asianpaint18.pricePerLitre);
		System.out.println(asianpaint18.finishType);
		System.out.println(asianpaint18.durability);
		System.out.println(asianpaint18.isWaterproof);
		System.out.println(asianpaint18.brand);
		System.out.println(asianpaint18.country);
		System.out.println(asianpaint18.rating);
		System.out.println(asianpaint18.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint19 = new AsianPaint("Indigo", 9, 240.0f, "Matte", 4.7f, true, "Asian", "India", 4, 3);
		System.out.println(asianpaint19.colorName);
		System.out.println(asianpaint19.quantity);
		System.out.println(asianpaint19.pricePerLitre);
		System.out.println(asianpaint19.finishType);
		System.out.println(asianpaint19.durability);
		System.out.println(asianpaint19.isWaterproof);
		System.out.println(asianpaint19.brand);
		System.out.println(asianpaint19.country);
		System.out.println(asianpaint19.rating);
		System.out.println(asianpaint19.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint20 = new AsianPaint("Olive", 7, 220.0f, "Glossy", 4.9f, true, "Asian", "India", 4, 3);
		System.out.println(asianpaint20.colorName);
		System.out.println(asianpaint20.quantity);
		System.out.println(asianpaint20.pricePerLitre);
		System.out.println(asianpaint20.finishType);
		System.out.println(asianpaint20.durability);
		System.out.println(asianpaint20.isWaterproof);
		System.out.println(asianpaint20.brand);
		System.out.println(asianpaint20.country);
		System.out.println(asianpaint20.rating);
		System.out.println(asianpaint20.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint21 = new AsianPaint("Beige", 5, 200.0f, "Matte", 3.5f, false, "Asian", "India", 3, 1);
		System.out.println(asianpaint21.colorName);
		System.out.println(asianpaint21.quantity);
		System.out.println(asianpaint21.pricePerLitre);
		System.out.println(asianpaint21.finishType);
		System.out.println(asianpaint21.durability);
		System.out.println(asianpaint21.isWaterproof);
		System.out.println(asianpaint21.brand);
		System.out.println(asianpaint21.country);
		System.out.println(asianpaint21.rating);
		System.out.println(asianpaint21.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint22 = new AsianPaint("Coral", 6, 210.0f, "Glossy", 3.9f, true, "Asian", "India", 3, 2);
		System.out.println(asianpaint22.colorName);
		System.out.println(asianpaint22.quantity);
		System.out.println(asianpaint22.pricePerLitre);
		System.out.println(asianpaint22.finishType);
		System.out.println(asianpaint22.durability);
		System.out.println(asianpaint22.isWaterproof);
		System.out.println(asianpaint22.brand);
		System.out.println(asianpaint22.country);
		System.out.println(asianpaint22.rating);
		System.out.println(asianpaint22.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint23 = new AsianPaint("Turquoise", 8, 230.0f, "Matte", 4.4f, true, "Asian", "India", 4, 2);
		System.out.println(asianpaint23.colorName);
		System.out.println(asianpaint23.quantity);
		System.out.println(asianpaint23.pricePerLitre);
		System.out.println(asianpaint23.finishType);
		System.out.println(asianpaint23.durability);
		System.out.println(asianpaint23.isWaterproof);
		System.out.println(asianpaint23.brand);
		System.out.println(asianpaint23.country);
		System.out.println(asianpaint23.rating);
		System.out.println(asianpaint23.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint24 = new AsianPaint("Mint", 7, 220.0f, "Glossy", 4.6f, true, "Asian", "India", 4, 3);
		System.out.println(asianpaint24.colorName);
		System.out.println(asianpaint24.quantity);
		System.out.println(asianpaint24.pricePerLitre);
		System.out.println(asianpaint24.finishType);
		System.out.println(asianpaint24.durability);
		System.out.println(asianpaint24.isWaterproof);
		System.out.println(asianpaint24.brand);
		System.out.println(asianpaint24.country);
		System.out.println(asianpaint24.rating);
		System.out.println(asianpaint24.warranty);
		System.out.println("=========================================");

		AsianPaint asianpaint25 = new AsianPaint("Peach", 6, 210.0f, "Matte", 3.7f, false, "Asian", "India", 3, 2);
		System.out.println(asianpaint25.colorName);
		System.out.println(asianpaint25.quantity);
		System.out.println(asianpaint25.pricePerLitre);
		System.out.println(asianpaint25.finishType);
		System.out.println(asianpaint25.durability);
		System.out.println(asianpaint25.isWaterproof);
		System.out.println(asianpaint25.brand);
		System.out.println(asianpaint25.country);
		System.out.println(asianpaint25.rating);
		System.out.println(asianpaint25.warranty);
		System.out.println("=========================================");
	}
}